name: Build and deploy to Azure

env:
  AZURE_WEBAPP_NAME: boozfinder-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '5.0.x'

on:
  push:
    branches:
      - master
      
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Build solution
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/boozfinder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/boozfinder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Get secrets  
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "boozfinder-kv"
          secrets: 'CosmosDb-Account,CosmosDb-ContainerName,CosmosDb-DatabaseName,CosmosDb-Key,TableStorage-Account,TableStorage-Key,TableStorage-TableName'
        id: boozfinder-secrets
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
        
      - name: Run variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: appsettings.json
        env:
          CosmosDb.Account: ${{ steps.boozfinder-secrets.outputs.CosmosDb-Account }}
          CosmosDb.Key: ${{ steps.boozfinder-secrets.outputs.CosmosDb-Key }}
          CosmosDb.DatabaseName: ${{ steps.boozfinder-secrets.outputs.CosmosDb-DatabaseName }}
          CosmosDb.ContainerName: ${{ steps.boozfinder-secrets.outputs.CosmosDb-ContainerName }}
          LogStorage.Account: ${{ steps.boozfinder-secrets.outputs.TableStorage-Account }}
          LogStorage.Key: ${{ steps.boozfinder-secrets.outputs.TableStorage-Key }}
          LogStorage.Name: ${{ steps.boozfinder-secrets.outputs.TableStorage-TableName }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
